spring:
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: create-drop
      #      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  batch: # batch 初始化表
    initialize-schema: always
