eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true


server:
  port: 7010

#spring:
#  application:
#    name: zuul-gateway
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0 #请求的采样率，在测试时为了方便查看可以改为1表示所有请求都记录，但在生产环境中还是建议改为0.1，否则数量太多影响性能

spring:
  application:
    name: zuul-gateway
  zipkin:
    base-url: http://localhost:19411  #zipkin+rabbitmq+es
    sender:
      type: rabbit   #kafka,rabbit,web
  sleuth:
    web:
      client:
        enabled: true  #默认为true
    sampler:
      probability: 1.0 #请求的采样率，在测试时为了方便查看可以改为1表示所有请求都记录，但在生产环境中还是建议改为0.1，否则数量太多影响性能
#  rabbitmq:
#    addresses: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: zipkin


zuul:
  routes:
    mycustomer:
      serviceId: consumer-core
      path: /consumer-zuul/**
    myprovider:
      serviceId: provider-api
      path: /provider-zuul/**
  prefix: /api   #注意前缀
  host:
    max-total-connections: 2000
    max-per-route-connections: 200
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000


security:
  oauth2:
    client:
      access-token-uri: http://localhost:1000/uaa/oauth/token #令牌端点
      user-authorization-uri: http://localhost:1000/uaa/oauth/authorize #授权端点
      client-id: liz-service #OAuth2客户端ID
      client-secret: secret #OAuth2客户端密钥
      grant-type: client_credentials,password
    resource:
      token-info-uri: http://localhost:1000/uaa/oauth/check_token
      user-info-uri: http://localhost:1000/uaa/user/current
#    resource:
#      jwt:
#        key-value: springcloud123 #使用对称加密方式，默认算法为HS256

