server:
  port: 9011

spring:
  application:
    name: stream-consumer-1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
#          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        #input是接收
        input:
          destination: stream-demo
          group: group-1 #相同的组只有一个可以消费
          consumer:
            partitioned: true #开启分区,只想要springcloud-stream2模块接收到消息，
        #进行消息中转处理后，在进行转发出去
        output:
          destination: stream-demo-trans
          content-type: application/json
        ack-input: # ack
          destination: stream-ack
        ack-output: # ack
          destination: stream-ack-trans

