server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:honeykee/springcloud-config.git #GitHub上面的git仓库名字
    bus: #开启bus
      trace:
        enabled: true
  rabbitmq:
    virtual-host: bus
    username: guest
    password: guest
    port: 5672
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

management: # 暴露所有actuator端口
  endpoints:
    web:
      exposure:
        include: "*"

